def product_data():
    return {
        "name": "Iphone 14 Pro Max",
        "quantity": 10,
        "price": "8.500",
        "status": True,
    }


def products_data():
    return [
        {"name": "Iphone 14 Pro Max", "quantity": 10, "price": "8.500", "status": True},
        {"name": "Iphone 14 Pro", "quantity": 5, "price": "7.500", "status": True},
        {"name": "Iphone 13", "quantity": 2, "price": "6.500", "status": True},
        {"name": "Iphone 12", "quantity": 1, "price": "5.500", "status": True},
        {
            "name": "Samsung Galaxy S23 Ultra",
            "quantity": 15,
            "price": "6.999",
            "status": True,
        },
        {"name": "Xiaomi 13 Pro", "quantity": 20, "price": "4.799", "status": True},
        {"name": "Motorola Edge 40", "quantity": 8, "price": "3.499", "status": True},
        {"name": "Asus ROG Phone 7", "quantity": 5, "price": "7.200", "status": True},
        {
            "name": "Google Pixel 7 Pro",
            "quantity": 12,
            "price": "5.999",
            "status": True,
        },
        {"name": "Sony Xperia 1 V", "quantity": 6, "price": "8.000", "status": True},
        {"name": "OnePlus 11", "quantity": 14, "price": "4.999", "status": True},
        {"name": "Realme GT Neo 5", "quantity": 18, "price": "3.200", "status": True},
        {"name": "Huawei P60 Pro", "quantity": 7, "price": "6.500", "status": True},
        {"name": "Iphone 13 Mini", "quantity": 9, "price": "4.800", "status": True},
        {
            "name": "Samsung Galaxy Z Fold 4",
            "quantity": 4,
            "price": "11.499",
            "status": True,
        },
        {
            "name": "Xiaomi Redmi Note 12",
            "quantity": 25,
            "price": "1.799",
            "status": True,
        },
        {"name": "Motorola G73", "quantity": 30, "price": "1.599", "status": True},
        {"name": "Asus Zenfone 10", "quantity": 11, "price": "3.899", "status": True},
        {"name": "Google Pixel 6a", "quantity": 16, "price": "2.499", "status": True},
        {"name": "Sony Xperia 5 IV", "quantity": 8, "price": "5.800", "status": True},
        {
            "name": "OnePlus Nord CE 3 Lite",
            "quantity": 21,
            "price": "1.899",
            "status": True,
        },
        {"name": "Realme 10 Pro+", "quantity": 17, "price": "2.399", "status": True},
        {"name": "Huawei Nova 11i", "quantity": 19, "price": "1.999", "status": True},
        {"name": "Iphone SE (2022)", "quantity": 13, "price": "3.199", "status": True},
        {
            "name": "Samsung Galaxy A54",
            "quantity": 26,
            "price": "2.099",
            "status": True,
        },
        {
            "name": "Xiaomi Poco X5 Pro",
            "quantity": 23,
            "price": "1.899",
            "status": True,
        },
        {
            "name": "Motorola Edge 30 Neo",
            "quantity": 14,
            "price": "2.499",
            "status": True,
        },
        {"name": "Asus ROG Phone 6", "quantity": 5, "price": "6.999", "status": True},
        {"name": "Google Pixel 5", "quantity": 10, "price": "2.799", "status": True},
        {"name": "Sony Xperia 10 IV", "quantity": 7, "price": "3.299", "status": True},
        {"name": "OnePlus 9 Pro", "quantity": 9, "price": "3.999", "status": True},
        {"name": "Realme C55", "quantity": 28, "price": "1.399", "status": True},
        {"name": "Huawei Mate 50 Pro", "quantity": 6, "price": "7.499", "status": True},
        {"name": "Iphone 12 Pro", "quantity": 8, "price": "5.500", "status": True},
        {
            "name": "Samsung Galaxy S21 FE",
            "quantity": 15,
            "price": "3.199",
            "status": True,
        },
        {
            "name": "Xiaomi Mi 11 Ultra",
            "quantity": 12,
            "price": "4.499",
            "status": True,
        },
        {"name": "Motorola Moto E13", "quantity": 32, "price": "899", "status": True},
        {"name": "Asus Zenfone 9", "quantity": 10, "price": "3.599", "status": True},
        {"name": "Google Pixel 4a", "quantity": 9, "price": "2.199", "status": True},
        {"name": "Sony Xperia L4", "quantity": 11, "price": "1.299", "status": True},
        {"name": "OnePlus 8T", "quantity": 13, "price": "2.799", "status": True},
        {"name": "Realme Narzo 50", "quantity": 27, "price": "1.199", "status": True},
        {"name": "Huawei P40 Lite", "quantity": 16, "price": "1.499", "status": True},
        {"name": "Iphone 11", "quantity": 14, "price": "3.199", "status": True},
        {
            "name": "Samsung Galaxy Note 20 Ultra",
            "quantity": 6,
            "price": "5.499",
            "status": True,
        },
        {
            "name": "Xiaomi Black Shark 5 Pro",
            "quantity": 8,
            "price": "4.999",
            "status": True,
        },
        {
            "name": "Motorola One Fusion",
            "quantity": 18,
            "price": "1.499",
            "status": True,
        },
        {"name": "Asus ROG Phone 5s", "quantity": 7, "price": "5.699", "status": True},
        {"name": "Google Pixel 3 XL", "quantity": 5, "price": "1.799", "status": True},
        {"name": "Sony Xperia XA2", "quantity": 9, "price": "1.099", "status": True},
        {"name": "OnePlus 7T", "quantity": 8, "price": "2.299", "status": True},
        {"name": "Realme 8", "quantity": 20, "price": "1.399", "status": True},
        {"name": "Huawei Y9a", "quantity": 15, "price": "1.199", "status": True},
    ]
